### ISSUE TITLE
CyNDEx fails to load browser in Ubuntu 18.04

### ISSUE THREAD

**Issue by dotasek** [idekerlab/fx-sample#48]
When first clicking on 'Export Collection to NDEx' from the collections context menu, CyNDEx2 attempts to download libraries and fails with the following exception:

05:08:50 SEVERE: There are next missing dependencies: 
	browsercore64 => libgconf-2.so.4
	libbrowsercore64.so => libgconf-2.so.4
05:08:50 SEVERE: Failed to start IPC process.
java.lang.IllegalStateException: Missing dependendecies have been detected. Check the log for details.
	at com.teamdev.jxbrowser.chromium.internal.ipc.ExternalChromiumProcessLinux.preProcessRun(SourceFile:3162)
	at com.teamdev.jxbrowser.chromium.internal.ipc.ExternalChromiumProcess.doStart(SourceFile:62)
	at com.teamdev.jxbrowser.chromium.internal.ipc.ChromiumProcess.start(SourceFile:235)
	at com.teamdev.jxbrowser.chromium.internal.ipc.d.run(SourceFile:196)
	at java.lang.Thread.run(Thread.java:748)
com.teamdev.jxbrowser.chromium.internal.ipc.IPCException: Failed to start IPC process.
	at com.teamdev.jxbrowser.chromium.internal.ipc.d.run(SourceFile:203)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Missing dependendecies have been detected. Check the log for details.
	at com.teamdev.jxbrowser.chromium.internal.ipc.ExternalChromiumProcessLinux.preProcessRun(SourceFile:3162)
	at com.teamdev.jxbrowser.chromium.internal.ipc.ExternalChromiumProcess.doStart(SourceFile:62)
	at com.teamdev.jxbrowser.chromium.internal.ipc.ChromiumProcess.start(SourceFile:235)
	at com.teamdev.jxbrowser.chromium.internal.ipc.d.run(SourceFile:196)
	... 1 more
17:08:50.963 ERROR [Thread-40] Failed to create browser instance for CyNDEx-2. Restart Cytoscape and try again.
Error: Failed to start IPC process.

**Comment by coleslaw481** [comment]
newer versions of cy-ndex no longer use jxbrowser. closing
